// Generates docs/fifa-world-cup-2026.ics — FIFA World Cup 2026 subscription calendar.
// Source kickoff times are US Eastern (ET). June/July 2026 ET = EDT = UTC-4,
// so UTC = ET + 4h. We build each Date in UTC by adding 4 to the ET hour and
// let Date normalize day/month rollovers. Events stored in UTC (Z) so every
// subscriber's phone localizes automatically.

const FLAGS = {
  Mexico: "🇲🇽",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  Czechia: "🇨🇿",
  Canada: "🇨🇦",
  "Bosnia & Herzegovina": "🇧🇦",
  Qatar: "🇶🇦",
  Switzerland: "🇨🇭",
  Brazil: "🇧🇷",
  Morocco: "🇲🇦",
  Haiti: "🇭🇹",
  Scotland: "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  USA: "🇺🇸",
  Paraguay: "🇵🇾",
  Australia: "🇦🇺",
  Turkey: "🇹🇷",
  Germany: "🇩🇪",
  "Ivory Coast": "🇨🇮",
  Ecuador: "🇪🇨",
  Curaçao: "🇨🇼",
  Netherlands: "🇳🇱",
  Sweden: "🇸🇪",
  Tunisia: "🇹🇳",
  Japan: "🇯🇵",
  Belgium: "🇧🇪",
  Egypt: "🇪🇬",
  Iran: "🇮🇷",
  "New Zealand": "🇳🇿",
  Spain: "🇪🇸",
  "Cape Verde": "🇨🇻",
  "Saudi Arabia": "🇸🇦",
  Uruguay: "🇺🇾",
  France: "🇫🇷",
  Senegal: "🇸🇳",
  Iraq: "🇮🇶",
  Norway: "🇳🇴",
  Argentina: "🇦🇷",
  Algeria: "🇩🇿",
  Austria: "🇦🇹",
  Jordan: "🇯🇴",
  Portugal: "🇵🇹",
  "DR Congo": "🇨🇩",
  Uzbekistan: "🇺🇿",
  Colombia: "🇨🇴",
  England: "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  Croatia: "🇭🇷",
  Ghana: "🇬🇭",
  Panama: "🇵🇦",
};

// [n, month, day, etHour24, etMin, home, away, groupLetter, venue, city]
const groupStage = [
  [
    1,
    6,
    11,
    15,
    0,
    "Mexico",
    "South Africa",
    "A",
    "Estadio Azteca",
    "Mexico City",
  ],
  [2, 6, 11, 22, 0, "South Korea", "Czechia", "A", "Estadio Akron", "Zapopan"],
  [
    3,
    6,
    12,
    15,
    0,
    "Canada",
    "Bosnia & Herzegovina",
    "B",
    "BMO Field",
    "Toronto",
  ],
  [4, 6, 12, 21, 0, "USA", "Paraguay", "D", "SoFi Stadium", "Inglewood"],
  [
    5,
    6,
    13,
    15,
    0,
    "Qatar",
    "Switzerland",
    "B",
    "Levi's Stadium",
    "Santa Clara",
  ],
  [
    6,
    6,
    13,
    18,
    0,
    "Brazil",
    "Morocco",
    "C",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [7, 6, 13, 21, 0, "Haiti", "Scotland", "C", "Gillette Stadium", "Foxborough"],
  [8, 6, 14, 0, 0, "Australia", "Turkey", "D", "BC Place", "Vancouver"],
  [9, 6, 14, 13, 0, "Germany", "Curaçao", "E", "NRG Stadium", "Houston"],
  [10, 6, 14, 16, 0, "Netherlands", "Japan", "F", "AT&T Stadium", "Arlington"],
  [
    11,
    6,
    14,
    19,
    0,
    "Ivory Coast",
    "Ecuador",
    "E",
    "Lincoln Financial Field",
    "Philadelphia",
  ],
  [12, 6, 14, 22, 0, "Sweden", "Tunisia", "F", "Estadio BBVA", "Monterrey"],
  [
    13,
    6,
    15,
    12,
    0,
    "Spain",
    "Cape Verde",
    "H",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [14, 6, 15, 15, 0, "Belgium", "Egypt", "G", "Lumen Field", "Seattle"],
  [
    15,
    6,
    15,
    18,
    0,
    "Saudi Arabia",
    "Uruguay",
    "H",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [16, 6, 15, 21, 0, "Iran", "New Zealand", "G", "SoFi Stadium", "Inglewood"],
  [
    17,
    6,
    16,
    15,
    0,
    "France",
    "Senegal",
    "I",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [18, 6, 16, 18, 0, "Iraq", "Norway", "I", "Gillette Stadium", "Foxborough"],
  [
    19,
    6,
    16,
    21,
    0,
    "Argentina",
    "Algeria",
    "J",
    "Arrowhead Stadium",
    "Kansas City",
  ],
  [20, 6, 17, 0, 0, "Austria", "Jordan", "J", "Levi's Stadium", "Santa Clara"],
  [21, 6, 17, 13, 0, "Portugal", "DR Congo", "K", "NRG Stadium", "Houston"],
  [22, 6, 17, 16, 0, "England", "Croatia", "L", "AT&T Stadium", "Arlington"],
  [23, 6, 17, 19, 0, "Ghana", "Panama", "L", "BMO Field", "Toronto"],
  [
    24,
    6,
    17,
    22,
    0,
    "Uzbekistan",
    "Colombia",
    "K",
    "Estadio Azteca",
    "Mexico City",
  ],
  [
    25,
    6,
    18,
    12,
    0,
    "Czechia",
    "South Africa",
    "A",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [
    26,
    6,
    18,
    15,
    0,
    "Switzerland",
    "Bosnia & Herzegovina",
    "B",
    "SoFi Stadium",
    "Inglewood",
  ],
  [27, 6, 18, 18, 0, "Canada", "Qatar", "B", "BC Place", "Vancouver"],
  [28, 6, 18, 21, 0, "Mexico", "South Korea", "A", "Estadio Akron", "Zapopan"],
  [29, 6, 19, 15, 0, "USA", "Australia", "D", "Lumen Field", "Seattle"],
  [
    30,
    6,
    19,
    18,
    0,
    "Scotland",
    "Morocco",
    "C",
    "Gillette Stadium",
    "Foxborough",
  ],
  [
    31,
    6,
    19,
    20,
    30,
    "Brazil",
    "Haiti",
    "C",
    "Lincoln Financial Field",
    "Philadelphia",
  ],
  [
    32,
    6,
    19,
    23,
    0,
    "Turkey",
    "Paraguay",
    "D",
    "Levi's Stadium",
    "Santa Clara",
  ],
  [33, 6, 20, 13, 0, "Netherlands", "Sweden", "F", "NRG Stadium", "Houston"],
  [34, 6, 20, 16, 0, "Germany", "Ivory Coast", "E", "BMO Field", "Toronto"],
  [
    35,
    6,
    20,
    20,
    0,
    "Ecuador",
    "Curaçao",
    "E",
    "Arrowhead Stadium",
    "Kansas City",
  ],
  [36, 6, 21, 0, 0, "Tunisia", "Japan", "F", "Estadio BBVA", "Monterrey"],
  [
    37,
    6,
    21,
    12,
    0,
    "Spain",
    "Saudi Arabia",
    "H",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [38, 6, 21, 15, 0, "Belgium", "Iran", "G", "SoFi Stadium", "Inglewood"],
  [
    39,
    6,
    21,
    18,
    0,
    "Uruguay",
    "Cape Verde",
    "H",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [40, 6, 21, 21, 0, "New Zealand", "Egypt", "G", "BC Place", "Vancouver"],
  [41, 6, 22, 13, 0, "Argentina", "Austria", "J", "AT&T Stadium", "Arlington"],
  [
    42,
    6,
    22,
    17,
    0,
    "France",
    "Iraq",
    "I",
    "Lincoln Financial Field",
    "Philadelphia",
  ],
  [
    43,
    6,
    22,
    20,
    0,
    "Norway",
    "Senegal",
    "I",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [44, 6, 22, 23, 0, "Jordan", "Algeria", "J", "Levi's Stadium", "Santa Clara"],
  [45, 6, 23, 13, 0, "Portugal", "Uzbekistan", "K", "NRG Stadium", "Houston"],
  [46, 6, 23, 16, 0, "England", "Ghana", "L", "Gillette Stadium", "Foxborough"],
  [47, 6, 23, 19, 0, "Panama", "Croatia", "L", "BMO Field", "Toronto"],
  [48, 6, 23, 22, 0, "Colombia", "DR Congo", "K", "Estadio Akron", "Zapopan"],
  [49, 6, 24, 15, 0, "Switzerland", "Canada", "B", "BC Place", "Vancouver"],
  [
    50,
    6,
    24,
    15,
    0,
    "Bosnia & Herzegovina",
    "Qatar",
    "B",
    "Lumen Field",
    "Seattle",
  ],
  [
    51,
    6,
    24,
    18,
    0,
    "Scotland",
    "Brazil",
    "C",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [
    52,
    6,
    24,
    18,
    0,
    "Morocco",
    "Haiti",
    "C",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [53, 6, 24, 21, 0, "Czechia", "Mexico", "A", "Estadio Azteca", "Mexico City"],
  [
    54,
    6,
    24,
    21,
    0,
    "South Africa",
    "South Korea",
    "A",
    "Estadio BBVA",
    "Monterrey",
  ],
  [
    55,
    6,
    25,
    16,
    0,
    "Curaçao",
    "Ivory Coast",
    "E",
    "Lincoln Financial Field",
    "Philadelphia",
  ],
  [
    56,
    6,
    25,
    16,
    0,
    "Ecuador",
    "Germany",
    "E",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [57, 6, 25, 19, 0, "Japan", "Sweden", "F", "AT&T Stadium", "Arlington"],
  [
    58,
    6,
    25,
    19,
    0,
    "Tunisia",
    "Netherlands",
    "F",
    "Arrowhead Stadium",
    "Kansas City",
  ],
  [59, 6, 25, 22, 0, "Turkey", "USA", "D", "SoFi Stadium", "Inglewood"],
  [
    60,
    6,
    25,
    22,
    0,
    "Paraguay",
    "Australia",
    "D",
    "Levi's Stadium",
    "Santa Clara",
  ],
  [61, 6, 26, 15, 0, "Norway", "France", "I", "Gillette Stadium", "Foxborough"],
  [62, 6, 26, 15, 0, "Senegal", "Iraq", "I", "BMO Field", "Toronto"],
  [
    63,
    6,
    26,
    20,
    0,
    "Cape Verde",
    "Saudi Arabia",
    "H",
    "NRG Stadium",
    "Houston",
  ],
  [64, 6, 26, 20, 0, "Uruguay", "Spain", "H", "Estadio Akron", "Zapopan"],
  [65, 6, 26, 23, 0, "Egypt", "Iran", "G", "Lumen Field", "Seattle"],
  [66, 6, 26, 23, 0, "New Zealand", "Belgium", "G", "BC Place", "Vancouver"],
  [
    67,
    6,
    27,
    17,
    0,
    "Panama",
    "England",
    "L",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [
    68,
    6,
    27,
    17,
    0,
    "Croatia",
    "Ghana",
    "L",
    "Lincoln Financial Field",
    "Philadelphia",
  ],
  [
    69,
    6,
    27,
    19,
    30,
    "Colombia",
    "Portugal",
    "K",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [
    70,
    6,
    27,
    19,
    30,
    "DR Congo",
    "Uzbekistan",
    "K",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [
    71,
    6,
    27,
    22,
    0,
    "Algeria",
    "Austria",
    "J",
    "Arrowhead Stadium",
    "Kansas City",
  ],
  [72, 6, 27, 22, 0, "Jordan", "Argentina", "J", "AT&T Stadium", "Arlington"],
];

// [n, month, day, etHour24, etMin, homeSlot, awaySlot, roundLabel, venue, city]
const knockout = [
  [
    73,
    6,
    28,
    15,
    0,
    "Runner-up Group A",
    "Runner-up Group B",
    "Round of 32",
    "SoFi Stadium",
    "Inglewood",
  ],
  [
    74,
    6,
    29,
    16,
    30,
    "Winner Group E",
    "Best Third (A/B/C/D/F)",
    "Round of 32",
    "Gillette Stadium",
    "Foxborough",
  ],
  [
    75,
    6,
    29,
    21,
    0,
    "Winner Group F",
    "Runner-up Group C",
    "Round of 32",
    "Estadio BBVA",
    "Monterrey",
  ],
  [
    76,
    6,
    29,
    13,
    0,
    "Winner Group C",
    "Runner-up Group F",
    "Round of 32",
    "NRG Stadium",
    "Houston",
  ],
  [
    77,
    6,
    30,
    17,
    0,
    "Winner Group I",
    "Best Third (C/D/F/G/H)",
    "Round of 32",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [
    78,
    6,
    30,
    13,
    0,
    "Runner-up Group E",
    "Runner-up Group I",
    "Round of 32",
    "AT&T Stadium",
    "Arlington",
  ],
  [
    79,
    6,
    30,
    21,
    0,
    "Winner Group A",
    "Best Third (C/E/F/H/I)",
    "Round of 32",
    "Estadio Azteca",
    "Mexico City",
  ],
  [
    80,
    7,
    1,
    12,
    0,
    "Winner Group L",
    "Best Third (E/H/I/J/K)",
    "Round of 32",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [
    81,
    7,
    1,
    20,
    0,
    "Winner Group D",
    "Best Third (B/E/F/I/J)",
    "Round of 32",
    "Levi's Stadium",
    "Santa Clara",
  ],
  [
    82,
    7,
    1,
    16,
    0,
    "Winner Group G",
    "Best Third (A/E/H/I/J)",
    "Round of 32",
    "Lumen Field",
    "Seattle",
  ],
  [
    83,
    7,
    2,
    19,
    0,
    "Runner-up Group K",
    "Runner-up Group L",
    "Round of 32",
    "BMO Field",
    "Toronto",
  ],
  [
    84,
    7,
    2,
    15,
    0,
    "Winner Group H",
    "Runner-up Group J",
    "Round of 32",
    "SoFi Stadium",
    "Inglewood",
  ],
  [
    85,
    7,
    2,
    23,
    0,
    "Winner Group B",
    "Best Third (E/F/G/I/J)",
    "Round of 32",
    "BC Place",
    "Vancouver",
  ],
  [
    86,
    7,
    3,
    18,
    0,
    "Winner Group J",
    "Runner-up Group H",
    "Round of 32",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [
    87,
    7,
    3,
    21,
    30,
    "Winner Group K",
    "Best Third (D/E/I/J/L)",
    "Round of 32",
    "Arrowhead Stadium",
    "Kansas City",
  ],
  [
    88,
    7,
    3,
    14,
    0,
    "Runner-up Group D",
    "Runner-up Group G",
    "Round of 32",
    "AT&T Stadium",
    "Arlington",
  ],
  [
    89,
    7,
    4,
    17,
    0,
    "Winner Match 74",
    "Winner Match 77",
    "Round of 16",
    "Lincoln Financial Field",
    "Philadelphia",
  ],
  [
    90,
    7,
    4,
    13,
    0,
    "Winner Match 73",
    "Winner Match 75",
    "Round of 16",
    "NRG Stadium",
    "Houston",
  ],
  [
    91,
    7,
    5,
    16,
    0,
    "Winner Match 76",
    "Winner Match 78",
    "Round of 16",
    "MetLife Stadium",
    "East Rutherford",
  ],
  [
    92,
    7,
    5,
    20,
    0,
    "Winner Match 79",
    "Winner Match 80",
    "Round of 16",
    "Estadio Azteca",
    "Mexico City",
  ],
  [
    93,
    7,
    6,
    15,
    0,
    "Winner Match 83",
    "Winner Match 84",
    "Round of 16",
    "AT&T Stadium",
    "Arlington",
  ],
  [
    94,
    7,
    6,
    20,
    0,
    "Winner Match 81",
    "Winner Match 82",
    "Round of 16",
    "Lumen Field",
    "Seattle",
  ],
  [
    95,
    7,
    7,
    12,
    0,
    "Winner Match 86",
    "Winner Match 88",
    "Round of 16",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [
    96,
    7,
    7,
    16,
    0,
    "Winner Match 85",
    "Winner Match 87",
    "Round of 16",
    "BC Place",
    "Vancouver",
  ],
  [
    97,
    7,
    9,
    16,
    0,
    "Winner Match 89",
    "Winner Match 90",
    "Quarter-final",
    "Gillette Stadium",
    "Foxborough",
  ],
  [
    98,
    7,
    10,
    15,
    0,
    "Winner Match 93",
    "Winner Match 94",
    "Quarter-final",
    "SoFi Stadium",
    "Inglewood",
  ],
  [
    99,
    7,
    11,
    17,
    0,
    "Winner Match 91",
    "Winner Match 92",
    "Quarter-final",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [
    100,
    7,
    11,
    21,
    0,
    "Winner Match 95",
    "Winner Match 96",
    "Quarter-final",
    "Arrowhead Stadium",
    "Kansas City",
  ],
  [
    101,
    7,
    14,
    15,
    0,
    "Winner Match 97",
    "Winner Match 98",
    "Semi-final",
    "AT&T Stadium",
    "Arlington",
  ],
  [
    102,
    7,
    15,
    15,
    0,
    "Winner Match 99",
    "Winner Match 100",
    "Semi-final",
    "Mercedes-Benz Stadium",
    "Atlanta",
  ],
  [
    103,
    7,
    18,
    17,
    0,
    "Loser Match 101",
    "Loser Match 102",
    "Third-place Play-off",
    "Hard Rock Stadium",
    "Miami Gardens",
  ],
  [
    104,
    7,
    19,
    15,
    0,
    "Winner Match 101",
    "Winner Match 102",
    "Final",
    "MetLife Stadium",
    "East Rutherford",
  ],
];

// Match results — add an entry after each match day.
// goals: { minute, player, team: "home" | "away", type?: "og" | "penalty", stoppage?: number }
const results = {
  1: {
    home: 2,
    away: 0,
    goals: [
      { minute: 9, player: "Julián Quiñones", team: "home" },
      { minute: 67, player: "Raúl Jiménez", team: "home" },
    ],
  },
  2: {
    home: 2,
    away: 1,
    goals: [
      { minute: 59, player: "Ladislav Krejčí", team: "away" },
      { minute: 67, player: "Hwang In-beom", team: "home" },
      { minute: 80, player: "Oh Hyeon-gyu", team: "home" },
    ],
  },
  3: {
    home: 1,
    away: 1,
    goals: [
      { minute: 21, player: "Jovo Lukic", team: "away" },
      { minute: 78, player: "Cyle Larin", team: "home" },
    ],
  },
  4: {
    home: 4,
    away: 1,
    goals: [
      { minute: 7, player: "Damián Bobadilla", team: "away", type: "og" },
      { minute: 31, player: "Folarin Balogun", team: "home" },
      { minute: 45, stoppage: 5, player: "Folarin Balogun", team: "home" },
      { minute: 73, player: "Mauricio", team: "away" },
      { minute: 90, stoppage: 8, player: "Giovanni Reyna", team: "home" },
    ],
  },
  5: {
    home: 1,
    away: 1,
    goals: [
      { minute: 17, player: "Breel Embolo", team: "away", type: "penalty" },
      { minute: 90, stoppage: 4, player: "Boualem Khoukhi", team: "home" },
    ],
  },
  6: {
    home: 1,
    away: 1,
    goals: [
      { minute: 21, player: "Ismael Saibari", team: "away" },
      { minute: 32, player: "Vinícius Júnior", team: "home" },
    ],
  },
  7: {
    home: 0,
    away: 1,
    goals: [{ minute: 28, player: "John McGinn", team: "away" }],
  },
  8: {
    home: 2,
    away: 0,
    goals: [
      { minute: 27, player: "Nestory Irankunda", team: "home" },
      { minute: 75, player: "Connor Metcalfe", team: "home" },
    ],
  },
  9: {
    home: 7,
    away: 1,
    goals: [
      { minute: 6, player: "Felix Nmecha", team: "home" },
      { minute: 21, player: "Livano Comenencia", team: "away" },
      { minute: 38, player: "Nico Schlotterbeck", team: "home" },
      { minute: 45, stoppage: 5, player: "Kai Havertz", team: "home", type: "penalty" },
      { minute: 47, player: "Jamal Musiala", team: "home" },
      { minute: 68, player: "Nathaniel Brown", team: "home" },
      { minute: 78, player: "Deniz Undav", team: "home" },
      { minute: 88, player: "Kai Havertz", team: "home" },
    ],
  },
  10: {
    home: 2,
    away: 2,
    goals: [
      { minute: 51, player: "Virgil van Dijk", team: "home" },
      { minute: 57, player: "Keito Nakamura", team: "away" },
      { minute: 64, player: "Crysencio Summerville", team: "home" },
      { minute: 89, player: "Daichi Kamada", team: "away" },
    ],
  },
  11: {
    home: 1,
    away: 0,
    goals: [{ minute: 90, player: "Amad Diallo", team: "home" }],
  },
  12: {
    home: 5,
    away: 1,
    goals: [
      { minute: 7, player: "Yasin Ayari", team: "home" },
      { minute: 30, player: "Alexander Isak", team: "home" },
      { minute: 43, player: "Omar Rekik", team: "away" },
      { minute: 59, player: "Viktor Gyökeres", team: "home" },
      { minute: 84, player: "Mattias Svanberg", team: "home" },
      { minute: 90, stoppage: 6, player: "Yasin Ayari", team: "home" },
    ],
  },
};

const pad = (n) => String(n).padStart(2, "0");

function icsNow() {
  const d = new Date();
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`;
}

function formatMinute({ minute, stoppage }) {
  if (stoppage != null) return `${minute}+${stoppage}`;
  return String(minute);
}

function formatMatchTitle(home, away, fh, fa, result) {
  if (!result) return `${fh} ${home} vs ${fa} ${away}`;
  return `${fh} ${home} ${result.home} x ${result.away} ${fa} ${away}`;
}

function formatMatchDescription(n, phase, prefix) {
  const line = `Match ${n} · FIFA World Cup 2026 · ${phase}`;
  return prefix ? `${prefix} · ${line}` : line;
}

function formatGoalSuffix(goal) {
  if (goal.type === "og") return " (OG)";
  if (goal.type === "penalty") return " (P)";
  return "";
}

function formatGoalLine(goal, home, away) {
  const teamName = goal.team === "home" ? home : away;
  const flag = FLAGS[teamName] || teamName;
  return `⚽ ${formatMinute(goal)}' ${goal.player} ${flag}${formatGoalSuffix(goal)}`;
}

function appendGoals(desc, goals, home, away) {
  if (!goals?.length) return desc;
  const lines = goals.map((g) => formatGoalLine(g, home, away));
  return `${desc}\n\nGoals:\n${lines.join("\n")}`;
}

function icsStamp(month, day, etHour, etMin) {
  // ET = UTC-4 in June/July; add 4h and let Date normalize rollovers.
  const d = new Date(Date.UTC(2026, month - 1, day, etHour + 4, etMin, 0));
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}00Z`;
}

function esc(s) {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

// RFC 5545 line folding at 75 octets (UTF-8 aware).
function fold(line) {
  const bytes = Buffer.from(line, "utf8");
  if (bytes.length <= 75) return line;
  const out = [];
  let start = 0;
  let limit = 75;
  while (start < bytes.length) {
    let end = Math.min(start + limit, bytes.length);
    // don't split a multi-byte char
    while (end < bytes.length && (bytes[end] & 0xc0) === 0x80) end--;
    out.push(bytes.slice(start, end).toString("utf8"));
    start = end;
    limit = 74; // continuation lines start with a space
  }
  return out.join("\r\n ");
}

function vevent({
  n,
  month,
  day,
  etHour,
  etMin,
  title,
  location,
  description,
  dtstamp = "20260611T000000Z",
}) {
  const start = icsStamp(month, day, etHour, etMin);
  const end = icsStamp(month, day, etHour + 2, etMin); // ~2h match window
  return [
    "BEGIN:VEVENT",
    fold(`UID:wc2026-m${n}@worldcup2026.calendar`),
    `DTSTAMP:${dtstamp}`,
    `DTSTART:${start}`,
    `DTEND:${end}`,
    fold(`SUMMARY:${esc(title)}`),
    fold(`LOCATION:${esc(location)}`),
    fold(`DESCRIPTION:${esc(description)}`),
    "TRANSP:TRANSPARENT",
    "END:VEVENT",
  ].join("\r\n");
}

const events = [];

for (const [
  n,
  month,
  day,
  etHour,
  etMin,
  home,
  away,
  grp,
  venue,
  city,
] of groupStage) {
  const fh = FLAGS[home] || "";
  const fa = FLAGS[away] || "";
  const result = results[n];
  const title = formatMatchTitle(home, away, fh, fa, result);
  let desc = formatMatchDescription(
    n,
    `Group ${grp}`,
    n === 1 ? "Opening Match" : undefined,
  );
  desc = appendGoals(desc, result?.goals, home, away);
  events.push(
    vevent({
      n,
      month,
      day,
      etHour,
      etMin,
      title,
      location: `${venue}, ${city}`,
      description: desc,
      dtstamp: result ? icsNow() : undefined,
    }),
  );
}

for (const [
  n,
  month,
  day,
  etHour,
  etMin,
  home,
  away,
  round,
  venue,
  city,
] of knockout) {
  const result = results[n];
  const title = result
    ? `${home} ${result.home} x ${result.away} ${away} — ${round}`
    : `${home} vs ${away} — ${round}`;
  let desc = formatMatchDescription(n, round);
  desc = appendGoals(desc, result?.goals, home, away);
  events.push(
    vevent({
      n,
      month,
      day,
      etHour,
      etMin,
      title,
      location: `${venue}, ${city}`,
      description: desc,
      dtstamp: result ? icsNow() : undefined,
    }),
  );
}

const calendar =
  [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//worldcup2026//FIFA World Cup 2026 Calendar//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:FIFA World Cup 2026",
    "X-WR-CALDESC:All 104 matches of the 2026 FIFA World Cup (USA · Canada · Mexico). Times localize to your device.",
    "X-WR-TIMEZONE:UTC",
    "REFRESH-INTERVAL;VALUE=DURATION:PT12H",
    "X-PUBLISHED-TTL:PT12H",
    ...events,
    "END:VCALENDAR",
  ].join("\r\n") + "\r\n";

require("fs").writeFileSync(
  __dirname + "/docs/fifa-world-cup-2026.ics",
  calendar,
  "utf8",
);
console.log(
  `Wrote docs/fifa-world-cup-2026.ics with ${events.length} matches.`,
);
